name: epson_pos_printer
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.nikkothe.epson_pos_printer
        pluginClass: EpsonPosPrinterPlugin
      ios:
        pluginClass: EpsonPosPrinterPlugin
      web:
        pluginClass: EpsonPosPrinterWeb
        fileName: epson_pos_printer_web.dart
  assets:
    - web/sdk/epos-2.27.0.js
